// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using category.CatData;

#nullable disable

namespace category.CatData.migrations
{
    [DbContext(typeof(Setcat))]
    [Migration("20240713071929_InitalCategories")]
    partial class InitalCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("category.Entities.CatEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cat_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cat_des")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cat_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cat_Table");
                });
#pragma warning restore 612, 618
        }
    }
}
